namePrefix: '{{ include "chart.fullname" . }}-'

namespace: '{{ .Release.Namespace | quote }}'

generatorOptions:
  disableNameSuffixHash: true

commonAnnotations:
  # Trick so kustomize does not split the annotation value
  cert-manager.io/inject-ca-from: '{{.Release.Namespace}}/{{. | include "chart.fullname"}}-serving-cert'

patchesStrategicMerge:
- validatingwebhook_endpoint_patch.yaml

patchesJson6902:
- target:
    version: v1beta1
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
  path: patch_validatingwebhook_name.yaml

bases:
- ../../webhook
