---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: mharbor.kb.io
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}'
      namespace: '{{ .Release.Namespace }}'
      port: '{{ .Values.service.port }}'
- name: mjobservice.kb.io
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}'
      namespace: '{{ .Release.Namespace }}'
      port: '{{ .Values.service.port }}'
- name: mharbor.kb.io
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}'
      namespace: '{{ .Release.Namespace }}'
      port: '{{ .Values.service.port }}'
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: vharbor.kb.io
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}'
      namespace: '{{ .Release.Namespace }}'
      port: '{{ .Values.service.port }}'
- name: vjobservice.kb.io
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}'
      namespace: '{{ .Release.Namespace }}'
      port: '{{ .Values.service.port }}'
- name: vregistry.kb.io
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}'
      namespace: '{{ .Release.Namespace }}'
      port: '{{ .Values.service.port }}'
