apiVersion: goharbor.io/v1alpha2
kind: Harbor
metadata:
  name: sample
spec:
  notary:
    migrationEnabled: true
  expose:
    notary:
      ingress:
        host: notary.harbor.domain
      tls:
        certificateRef: sample-public-certificate
