apiVersion: goharbor.io/v1alpha3
kind: Harbor
metadata:
  name: sample
spec:
  chartmuseum: {}
  imageChartStorage:
    filesystem:
      chartPersistentVolume:
        claimName: sample-harbor-chart
