apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  sample: "true"

resources:
- storage.yaml

bases:
- ../harbor

patchesStrategicMerge:
- harbor_chartmuseum_patch.yaml
- harbor_notary_patch.yaml
