apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $path, $_ :=  .Files.Glob "assets/*" }}
  {{ base $path }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
