# This assigns a PR to its author
addAssignees: true

addReviewers: false

reviewers:
  - holyhope
  - sguyennet
  - jMonsinjon
  - steven-zou
  - mhurtrel
  - heww
  - bitsf
  - wangcanfengxs
  - Ghostbaby
  - soulseen
  - chlins
  - XavierDuthil
  - cndoit18
  - lubronzhan
  - yxxhero
  - wy65701436
  - MarcelMue

options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - wip
    - DO NOT MERGE
  enable_group_assignment: true
  number_of_reviewers: 2
