addAssignees: false

addReviewers: true

useReviewGroups: true

reviewGroups:
  active:
    - MarcelMue
    - thcdrt
  general:
    - holyhope
    - steven-zou
    - bitsf
    - wy65701436

skipKeywords:
  - WIP
  - wip
  - DO NOT MERGE

numberOfReviewers: 1
