run:
  deadline: 10m
  modules-download-mode: readonly
issue:
  exclude-files:
  - pkged.go
  - ".*/zz_generated.*\\.go"
  exclude-dirs:
  - bin
  - dist

linters:
  enable:
  - asciicheck
  - bodyclose
  - dogsled
  - dupl
  - errcheck
  - errorlint
  - exhaustive
  - gochecknoinits
  - goconst
  - gocyclo
  - gofmt
  - goheader
  - goimports
  - gomodguard
  - goprintffuncname
  - gosimple
  - ineffassign
  # - interfacer
  # - maligned
  - misspell
  - noctx
  - prealloc
  - rowserrcheck
  - sqlclosecheck
  - stylecheck
  - testpackage
  - tparallel
  - typecheck
  - unconvert
  - unused
  disable:
  - gocognit
  - err113
  - nestif
  - gocritic
  - funlen
  - godot
  - gci
  - whitespace
  - unparam
  - nlreturn
  - gofumpt
  - wsl
  - govet
  - gosec
  - nakedret
  - nolintlint
  - revive
  - depguard
  - staticcheck
  - lll
  - gochecknoglobals
  - godox
  - paralleltest
  - wrapcheck
#  - errorlint
#  - goerr113
#  - gomnd
#  - nestif
#  - funlen
#  - gosec

service:
  golangci-lint-version: 1.45.x
  prepare:
  - make generate

issues:
  max-same-issues: 0
  max-issues-per-linter: 0

  exclude-rules:
  # Exclude some linters from running on tests files.
  - path: _test\.go
    linters:
    - dupl
    - funlen
    - gci
    - goerr113
    - gomnd
  - path: controllers/goharbor/internal/test
    linters:
    - dupl
    - funlen
    - gci
    - gomnd
