apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: sample-signer-ca
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sample-signer-ca
spec:
  secretName: sample-signer-ca
  organization:
  - goharbor
  isCA: true
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - server auth
  - client auth
  dnsNames:
  - notary.harbor.public
  issuerRef:
    name: sample-signer-ca
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: sample-signer
spec:
  ca:
    secretName: sample-signer-ca

