apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'leader-election-rolebinding'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.serviceAccountName" . | quote }}'
  namespace: '{{ .Release.Namespace | quote }}'
