apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-harbor-chart
  labels:
    goharbor.io/component: chart
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-harbor-trivy-reports
  labels:
    goharbor.io/component: trivy-reports
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-harbor-trivy-cache
  labels:
    goharbor.io/component: trivy-cache
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi