apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: '{{ include "chart.fullname" . }}-certificate'
