apiVersion: goharbor.io/v1alpha2
kind: Trivy
metadata:
  name: sample
spec:
  cache:
    redis:
      host: "harbor-redis-master"
      port: 6379
      database: 5
      passwordRef: harbor-redis
  server: {}
