apiVersion: v1
appVersion: 1.6.3
description: Postgres Operator creates and manages PostgreSQL clusters running in
  Kubernetes
home: https://github.com/zalando/postgres-operator
keywords:
- postgres
- operator
- cloud-native
- patroni
- spilo
maintainers:
- email: opensource@zalando.de
  name: Zalando
name: postgres-operator
sources:
- https://github.com/zalando/postgres-operator
version: 1.6.3
