{{- /* https://github.com/goharbor/harbor/blob/master/make/photon/prepare/templates/jobservice/config.yml.jinja */ -}}
protocol: "http"
port: {{ env.Getenv "PORT" }}

worker_pool:
  backend: "redis"

  redis_pool:
    namespace: jobservice

job_loggers:
- name: STD_OUTPUT
  level: {{ env.Getenv "LOG_LEVEL" "INFO" | toUpper | quote }}

    # JobService read files to expose logs
- name: FILE
  level: {{ env.Getenv "LOG_LEVEL" ( env.Getenv "PUBLIC_LOG_LEVEL" "INFO") | toUpper | quote }}
  settings: # Customized settings of logger
    base_dir: {{ env.Getenv "LOGS_DIR" | quote }}
  sweeper:
    duration: 7 #days
    settings: # Customized settings of sweeper
      work_dir: {{ env.Getenv "LOGS_DIR" | quote }}

loggers:
- name: STD_OUTPUT
  level: {{ env.Getenv "LOG_LEVEL" "INFO" | toUpper | quote }}

webhook:
  job_max_retry: 10
