# permissions to do viewer portals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portal-viewer-role
rules:
- apiGroups:
  - goharbor.io
  resources:
  - portals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - portals/status
  verbs:
  - get
