# permissions for end users to view robotaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: robotaccount-viewer-role
rules:
- apiGroups:
  - goharbor.io
  resources:
  - robotaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - robotaccounts/status
  verbs:
  - get
