version: 0.1
log:
  accesslog:
    disabled: true
  level: info
  formatter: json
http:
  debug:
    addr: {{ env.Getenv "METRICS_ADDRESS" | quote }}
    prometheus:
      enabled: true
      path: /metrics
  headers:
    X-Content-Type-Options: [nosniff]
  net: tcp
  addr: {{ env.Getenv "API_ADDRESS" | quote }}
  prefix: /
health:
  storagedriver:
    enabled: false
    interval: 10s
    threshold: 3
notifications:
  endpoints:
  - name: harbor-core
    disabled: false
    url: {{ env.Getenv "CORE_HOSTNAME" | printf "http://%s/service/notifications" | quote }}
    timeout: 3000ms
    threshold: 5
    backoff: 1s
    ignoredmediatypes:
    - application/vnd.docker.image.rootfs.diff.tar.gzip
    - application/vnd.docker.image.rootfs.foreign.diff.tar.gzip
    - application/vnd.oci.image.layer.v1.tar
    - application/vnd.oci.image.layer.v1.tar+gzip
    - application/vnd.oci.image.layer.v1.tar+zstd
    - application/vnd.oci.image.layer.nondistributable.v1.tar
    - application/vnd.oci.image.layer.nondistributable.v1.tar+gzip
    - application/vnd.oci.image.layer.nondistributable.v1.tar+zstd
    - application/octet-stream
auth:
  token:
    issuer: harbor-token-issuer
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry

{{- $redisUrl := env.Getenv "REDIS_URL" }}
{{- if gt ( len $redisUrl ) 0 }}
  {{- with (conv.URL $redisUrl) }}
redis:
  addr: {{ quote .Host }}
  {{- if strings.Contains "@" . }}
    {{- /* cannot get password from $redis.User.Password, only a single non error result is permitted */ -}}
    {{- with ( index ( strings.SplitN "@" 2 ( index ( strings.SplitN "/" 2 ( index ( strings.SplitN "://" 2 .String ) 1 ) ) 0 ) ) 0 ) }}
  password: {{ index ( strings.SplitN ":" 2 . ) 1 | quote }}
    {{- end }}
  {{- end }}
  db: {{ conv.ToInt .Path }}
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  {{- end }}
{{- end }}

validation:
  disabled: true
compatibility:
  schema1:
    enabled: true

storage:
  delete:
    enabled: true
  redirect:
    disable: {{ env.Getenv "STORAGE_DISABLE_REDIRECT" }}
  cache:
    blobdescriptor: {{ if gt ( len $redisUrl ) 0 -}} redis {{- else -}} inmemory {{- end }}
  maintenance:
    uploadpurging:
      enabled: false
    readonly:
      enabled: false
{{- range file.Walk ( env.Getenv "CONFIG_PATH" ) }}
  {{- if not ( file.IsDir . ) }}
    {{- "\n" -}}{{ filepath.Base . }}:
    {{- "\n" -}}{{ file.Read . | data.YAML | data.ToYAML | strings.Indent 1 "  " }}
  {{- end }}
{{- end }}
