apiVersion: goharbor.io/v1alpha2
kind: Harbor
metadata:
  name: sample
spec:
  harborAdminPasswordRef: admin-core-secret
  externalURL: http://core.harbor.domain
  expose:
    ingress:
      hosts:
        core: core.harbor.domain
        notary: notary.harbor.domain
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
  encryptionKeyRef: core-database-encryption
  portal: {}
  registry: {}
  core:
    tokenIssuer:
      name: service-token
      kind: Issuer
  redis:
    address: harbor-redis-master
    passwordRef: harbor-redis
  database:
    host: harbor-database-postgresql
    port: 5432
    username: postgres
    passwordRef: harbor-database-postgresql
