apiVersion: goharbor.io/v1alpha2
kind: Harbor
metadata:
  name: sample
spec:
  harborAdminPasswordRef: admin-core-secret
  externalURL: https://core.harbor.domain
  expose:
    core:
      ingress:
        host: core.harbor.domain
      tls:
        certificateRef: sample-public-certificate
  encryptionKeyRef: core-database-encryption
  internalTLS:
    enabled: true
  portal: {}
  registry: {}
  core:
    tokenIssuer:
      name: service-token
      kind: Issuer
  redis:
    address: harbor-redis-master
    passwordRef: harbor-redis
  database:
    hosts:
    - host: harbor-database-postgresql
      port: 5432
    username: postgres
    passwordRef: harbor-database-password
    sslMode: disable
  imageChartStorage:
    filesystem:
      registryPersistentVolume:
        claimName: sample-harbor-registry
