apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: harbor-sample
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: harbor-ca
spec:
  isCA: true
  issuerRef:
    name: harbor-sample
  secretName: harbor-sample-ca
  commonName: harbor-sample
