apiVersion: goharbor.io/v1alpha2
kind: Trivy
metadata:
  annotations:
    harbor.goharbor.io/version: ""
  creationTimestamp: null
  name: example-harbor
  namespace: default
spec:
  log: {}
  redis:
    database: 5
    host: 127.0.0.1
    jobs: {}
    pool: {}
    port: 3306
  resources: {}
  server:
    tokenServiceCertificateAuthorityRefs:
    - harbor-tls
  storage:
    cache:
      volumeSource:
        emptyDir: {}
    reports:
      volumeSource:
        emptyDir: {}
  update:
    skip: false
status:
  conditions: []
  operator: {}
