apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  sample: "true"

patchesStrategicMerge:
- server_trustservice_patch.yaml

resources:
- notaryserver-certificate.yaml

bases:
- ../notary-server
- ../notary-signer

