apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  sample: "true"

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: github-token
  literals:
  - secret=$(GITHUB_TOKEN)
  type: "goharbor.io/single-secret"

resources:
- goharbor_v1alpha2_notaryserver.yaml

