// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Annotations annotations
//
// swagger:model Annotations
type Annotations map[string]string

// Validate validates this annotations
func (m Annotations) Validate(formats strfmt.Registry) error {
	return nil
}
