// Code generated by go-swagger; DO NOT EDIT.

package scanners

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostScannersReader is a Reader for the PostScanners structure.
type PostScannersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostScannersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostScannersCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostScannersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostScannersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostScannersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostScannersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostScannersCreated creates a PostScannersCreated with default headers values
func NewPostScannersCreated() *PostScannersCreated {
	return &PostScannersCreated{}
}

/*PostScannersCreated handles this case with default header values.

Created successfully
*/
type PostScannersCreated struct {
	/*The URL of the created resource
	 */
	Location string
}

func (o *PostScannersCreated) Error() string {
	return fmt.Sprintf("[POST /scanners][%d] postScannersCreated ", 201)
}

func (o *PostScannersCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	return nil
}

// NewPostScannersBadRequest creates a PostScannersBadRequest with default headers values
func NewPostScannersBadRequest() *PostScannersBadRequest {
	return &PostScannersBadRequest{}
}

/*PostScannersBadRequest handles this case with default header values.

Bad registration request
*/
type PostScannersBadRequest struct {
}

func (o *PostScannersBadRequest) Error() string {
	return fmt.Sprintf("[POST /scanners][%d] postScannersBadRequest ", 400)
}

func (o *PostScannersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostScannersUnauthorized creates a PostScannersUnauthorized with default headers values
func NewPostScannersUnauthorized() *PostScannersUnauthorized {
	return &PostScannersUnauthorized{}
}

/*PostScannersUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostScannersUnauthorized struct {
}

func (o *PostScannersUnauthorized) Error() string {
	return fmt.Sprintf("[POST /scanners][%d] postScannersUnauthorized ", 401)
}

func (o *PostScannersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostScannersForbidden creates a PostScannersForbidden with default headers values
func NewPostScannersForbidden() *PostScannersForbidden {
	return &PostScannersForbidden{}
}

/*PostScannersForbidden handles this case with default header values.

Request is not allowed, system role required
*/
type PostScannersForbidden struct {
}

func (o *PostScannersForbidden) Error() string {
	return fmt.Sprintf("[POST /scanners][%d] postScannersForbidden ", 403)
}

func (o *PostScannersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostScannersInternalServerError creates a PostScannersInternalServerError with default headers values
func NewPostScannersInternalServerError() *PostScannersInternalServerError {
	return &PostScannersInternalServerError{}
}

/*PostScannersInternalServerError handles this case with default header values.

Internal server error happened
*/
type PostScannersInternalServerError struct {
}

func (o *PostScannersInternalServerError) Error() string {
	return fmt.Sprintf("[POST /scanners][%d] postScannersInternalServerError ", 500)
}

func (o *PostScannersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
