apiVersion: v1
data:
  secret: SGFyYm9yMTIzNDU=
kind: Secret
metadata:
  labels:
    sample: "true"
  name: admin-core-secret-7274ck5bh5
type: goharbor.io/single-secret
---
apiVersion: v1
data:
  secret: MTIzNDU2Nzg5MDEyMzQ1Ng==
kind: Secret
metadata:
  labels:
    sample: "true"
  name: core-database-encryption-dddh7f9gfg
type: goharbor.io/single-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sample: "true"
  name: sample-harbor-chart
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sample: "true"
  name: sample-harbor-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sample: "true"
  name: sample-harbor-trivy-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sample: "true"
  name: sample-harbor-trivy-reports
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    sample: "true"
  name: sample-public-certificate
spec:
  dnsNames:
  - core.harbor.domain
  - notary.harbor.domain
  isCA: true
  issuerRef:
    name: sample-public-certificate
  secretName: sample-public-certificate
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    sample: "true"
  name: sample-public-certificate
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    sample: "true"
  name: service-token
spec:
  selfSigned: {}
---
apiVersion: goharbor.io/v1alpha3
kind: HarborCluster
metadata:
  labels:
    sample: "true"
  name: harborcluster-sample
spec:
  chartmuseum: {}
  core:
    tokenIssuer:
      kind: Issuer
      name: service-token
  database:
    hosts:
    - host: harbor-database-postgresql
      port: 5432
    passwordRef: harbor-database-password
    sslMode: disable
    username: postgres
  encryptionKeyRef: core-database-encryption-dddh7f9gfg
  expose:
    core:
      ingress:
        host: core.harbor.domain
      tls:
        certificateRef: sample-public-certificate
    notary:
      ingress:
        host: notary.harbor.domain
      tls:
        certificateRef: sample-public-certificate
  externalURL: https://core.harbor.domain
  harborAdminPasswordRef: admin-core-secret-7274ck5bh5
  imageChartStorage:
    filesystem:
      chartPersistentVolume:
        claimName: sample-harbor-chart
      registryPersistentVolume:
        claimName: sample-harbor-registry
  imageSource:
    repository: ghcr.io/goharbor
  internalTLS:
    enabled: true
  logLevel: info
  notary:
    migrationEnabled: true
  portal: {}
  redis:
    host: harbor-redis-master
    passwordRef: harbor-redis
    port: 6379
  registry: {}
  trivy:
    skipUpdate: false
    storage:
      cachePersistentVolume:
        claimName: sample-harbor-trivy-cache
      reportsPersistentVolume:
        claimName: sample-harbor-trivy-reports
