apiVersion: goharbor.io/v1beta1
kind: Harbor
metadata:
  name: example
  namespace: default
spec:
  redis:
    host: 127.0.0.1
    port: 3306
  version: 2.4.0
  database:
    hosts:
      - host: 127.0.0.1