apiVersion: goharbor.io/v1alpha3
kind: Harbor
metadata:
  name: example
  namespace: default
spec:
  imageSource:
    repository: example.goharbor.io/goharbor
  redis:
    host: 127.0.0.1
    port: 3306
  version: 2.2.1
