// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LdapUsers ldap users
//
// swagger:model LdapUsers
type LdapUsers struct {

	// system will try to guess the user email address form "mail" or "email" attribute.
	LdapEmail string `json:"ldap_email,omitempty"`

	// system will try to guess the user realname form "uid" or "cn" attribute.
	LdapRealname string `json:"ldap_realname,omitempty"`

	// search ldap user name based on ldapconf.
	LdapUsername string `json:"ldap_username,omitempty"`
}

// Validate validates this ldap users
func (m *LdapUsers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LdapUsers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LdapUsers) UnmarshalBinary(b []byte) error {
	var res LdapUsers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
