// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Stats Stats provides the overall progress of the scan all process.
//
// swagger:model Stats
type Stats struct {

	// The number of the finished scan processes triggered by the scan all action
	Completed int64 `json:"completed,omitempty"`

	// The metrics data for the each status
	Metrics map[string]int64 `json:"metrics,omitempty"`

	// The requester identity which usually uses the ID of the scan all job
	Requester string `json:"requester,omitempty"`

	// The total number of scan processes triggered by the scan all action
	Total int64 `json:"total,omitempty"`
}

// Validate validates this stats
func (m *Stats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Stats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Stats) UnmarshalBinary(b []byte) error {
	var res Stats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
