// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TriggerSettings trigger settings
//
// swagger:model TriggerSettings
type TriggerSettings struct {

	// The cron string for scheduled trigger
	Cron string `json:"cron,omitempty"`
}

// Validate validates this trigger settings
func (m *TriggerSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TriggerSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TriggerSettings) UnmarshalBinary(b []byte) error {
	var res TriggerSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
