apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: console
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-env
$patch: delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-sa-binding
$patch: delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-sa-role
$patch: delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-sa
$patch: delete