apiVersion: goharbor.io/v1alpha2
kind: ChartMuseum
metadata:
  name: sample
spec:
  chart:
    url: https://harbor.public/chartrepo
    storage:
      filesystem:
        prefix: /charts
        volumeSource:
          emptyDir: {}
