// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteReplicationPoliciesIDReader is a Reader for the DeleteReplicationPoliciesID structure.
type DeleteReplicationPoliciesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteReplicationPoliciesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteReplicationPoliciesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteReplicationPoliciesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteReplicationPoliciesIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteReplicationPoliciesIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteReplicationPoliciesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewDeleteReplicationPoliciesIDPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteReplicationPoliciesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteReplicationPoliciesIDOK creates a DeleteReplicationPoliciesIDOK with default headers values
func NewDeleteReplicationPoliciesIDOK() *DeleteReplicationPoliciesIDOK {
	return &DeleteReplicationPoliciesIDOK{}
}

/*DeleteReplicationPoliciesIDOK handles this case with default header values.

Success
*/
type DeleteReplicationPoliciesIDOK struct {
}

func (o *DeleteReplicationPoliciesIDOK) Error() string {
	return fmt.Sprintf("[DELETE /replication/policies/{id}][%d] deleteReplicationPoliciesIdOK ", 200)
}

func (o *DeleteReplicationPoliciesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteReplicationPoliciesIDBadRequest creates a DeleteReplicationPoliciesIDBadRequest with default headers values
func NewDeleteReplicationPoliciesIDBadRequest() *DeleteReplicationPoliciesIDBadRequest {
	return &DeleteReplicationPoliciesIDBadRequest{}
}

/*DeleteReplicationPoliciesIDBadRequest handles this case with default header values.

Bad Request
*/
type DeleteReplicationPoliciesIDBadRequest struct {
}

func (o *DeleteReplicationPoliciesIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /replication/policies/{id}][%d] deleteReplicationPoliciesIdBadRequest ", 400)
}

func (o *DeleteReplicationPoliciesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteReplicationPoliciesIDUnauthorized creates a DeleteReplicationPoliciesIDUnauthorized with default headers values
func NewDeleteReplicationPoliciesIDUnauthorized() *DeleteReplicationPoliciesIDUnauthorized {
	return &DeleteReplicationPoliciesIDUnauthorized{}
}

/*DeleteReplicationPoliciesIDUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteReplicationPoliciesIDUnauthorized struct {
}

func (o *DeleteReplicationPoliciesIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /replication/policies/{id}][%d] deleteReplicationPoliciesIdUnauthorized ", 401)
}

func (o *DeleteReplicationPoliciesIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteReplicationPoliciesIDForbidden creates a DeleteReplicationPoliciesIDForbidden with default headers values
func NewDeleteReplicationPoliciesIDForbidden() *DeleteReplicationPoliciesIDForbidden {
	return &DeleteReplicationPoliciesIDForbidden{}
}

/*DeleteReplicationPoliciesIDForbidden handles this case with default header values.

Forbidden
*/
type DeleteReplicationPoliciesIDForbidden struct {
}

func (o *DeleteReplicationPoliciesIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /replication/policies/{id}][%d] deleteReplicationPoliciesIdForbidden ", 403)
}

func (o *DeleteReplicationPoliciesIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteReplicationPoliciesIDNotFound creates a DeleteReplicationPoliciesIDNotFound with default headers values
func NewDeleteReplicationPoliciesIDNotFound() *DeleteReplicationPoliciesIDNotFound {
	return &DeleteReplicationPoliciesIDNotFound{}
}

/*DeleteReplicationPoliciesIDNotFound handles this case with default header values.

Not Found
*/
type DeleteReplicationPoliciesIDNotFound struct {
}

func (o *DeleteReplicationPoliciesIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /replication/policies/{id}][%d] deleteReplicationPoliciesIdNotFound ", 404)
}

func (o *DeleteReplicationPoliciesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteReplicationPoliciesIDPreconditionFailed creates a DeleteReplicationPoliciesIDPreconditionFailed with default headers values
func NewDeleteReplicationPoliciesIDPreconditionFailed() *DeleteReplicationPoliciesIDPreconditionFailed {
	return &DeleteReplicationPoliciesIDPreconditionFailed{}
}

/*DeleteReplicationPoliciesIDPreconditionFailed handles this case with default header values.

Precondition Failed
*/
type DeleteReplicationPoliciesIDPreconditionFailed struct {
}

func (o *DeleteReplicationPoliciesIDPreconditionFailed) Error() string {
	return fmt.Sprintf("[DELETE /replication/policies/{id}][%d] deleteReplicationPoliciesIdPreconditionFailed ", 412)
}

func (o *DeleteReplicationPoliciesIDPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteReplicationPoliciesIDInternalServerError creates a DeleteReplicationPoliciesIDInternalServerError with default headers values
func NewDeleteReplicationPoliciesIDInternalServerError() *DeleteReplicationPoliciesIDInternalServerError {
	return &DeleteReplicationPoliciesIDInternalServerError{}
}

/*DeleteReplicationPoliciesIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteReplicationPoliciesIDInternalServerError struct {
}

func (o *DeleteReplicationPoliciesIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /replication/policies/{id}][%d] deleteReplicationPoliciesIdInternalServerError ", 500)
}

func (o *DeleteReplicationPoliciesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
