// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteProjectsProjectIDMembersMidReader is a Reader for the DeleteProjectsProjectIDMembersMid structure.
type DeleteProjectsProjectIDMembersMidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProjectsProjectIDMembersMidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteProjectsProjectIDMembersMidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteProjectsProjectIDMembersMidBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteProjectsProjectIDMembersMidUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteProjectsProjectIDMembersMidForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteProjectsProjectIDMembersMidInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteProjectsProjectIDMembersMidOK creates a DeleteProjectsProjectIDMembersMidOK with default headers values
func NewDeleteProjectsProjectIDMembersMidOK() *DeleteProjectsProjectIDMembersMidOK {
	return &DeleteProjectsProjectIDMembersMidOK{}
}

/*DeleteProjectsProjectIDMembersMidOK handles this case with default header values.

Project member deleted successfully.
*/
type DeleteProjectsProjectIDMembersMidOK struct {
}

func (o *DeleteProjectsProjectIDMembersMidOK) Error() string {
	return fmt.Sprintf("[DELETE /projects/{project_id}/members/{mid}][%d] deleteProjectsProjectIdMembersMidOK ", 200)
}

func (o *DeleteProjectsProjectIDMembersMidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProjectsProjectIDMembersMidBadRequest creates a DeleteProjectsProjectIDMembersMidBadRequest with default headers values
func NewDeleteProjectsProjectIDMembersMidBadRequest() *DeleteProjectsProjectIDMembersMidBadRequest {
	return &DeleteProjectsProjectIDMembersMidBadRequest{}
}

/*DeleteProjectsProjectIDMembersMidBadRequest handles this case with default header values.

The project id or project member id is invalid.
*/
type DeleteProjectsProjectIDMembersMidBadRequest struct {
}

func (o *DeleteProjectsProjectIDMembersMidBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /projects/{project_id}/members/{mid}][%d] deleteProjectsProjectIdMembersMidBadRequest ", 400)
}

func (o *DeleteProjectsProjectIDMembersMidBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProjectsProjectIDMembersMidUnauthorized creates a DeleteProjectsProjectIDMembersMidUnauthorized with default headers values
func NewDeleteProjectsProjectIDMembersMidUnauthorized() *DeleteProjectsProjectIDMembersMidUnauthorized {
	return &DeleteProjectsProjectIDMembersMidUnauthorized{}
}

/*DeleteProjectsProjectIDMembersMidUnauthorized handles this case with default header values.

User need to log in first.
*/
type DeleteProjectsProjectIDMembersMidUnauthorized struct {
}

func (o *DeleteProjectsProjectIDMembersMidUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /projects/{project_id}/members/{mid}][%d] deleteProjectsProjectIdMembersMidUnauthorized ", 401)
}

func (o *DeleteProjectsProjectIDMembersMidUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProjectsProjectIDMembersMidForbidden creates a DeleteProjectsProjectIDMembersMidForbidden with default headers values
func NewDeleteProjectsProjectIDMembersMidForbidden() *DeleteProjectsProjectIDMembersMidForbidden {
	return &DeleteProjectsProjectIDMembersMidForbidden{}
}

/*DeleteProjectsProjectIDMembersMidForbidden handles this case with default header values.

User in session does not have permission to the project.
*/
type DeleteProjectsProjectIDMembersMidForbidden struct {
}

func (o *DeleteProjectsProjectIDMembersMidForbidden) Error() string {
	return fmt.Sprintf("[DELETE /projects/{project_id}/members/{mid}][%d] deleteProjectsProjectIdMembersMidForbidden ", 403)
}

func (o *DeleteProjectsProjectIDMembersMidForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProjectsProjectIDMembersMidInternalServerError creates a DeleteProjectsProjectIDMembersMidInternalServerError with default headers values
func NewDeleteProjectsProjectIDMembersMidInternalServerError() *DeleteProjectsProjectIDMembersMidInternalServerError {
	return &DeleteProjectsProjectIDMembersMidInternalServerError{}
}

/*DeleteProjectsProjectIDMembersMidInternalServerError handles this case with default header values.

Unexpected internal errors.
*/
type DeleteProjectsProjectIDMembersMidInternalServerError struct {
}

func (o *DeleteProjectsProjectIDMembersMidInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /projects/{project_id}/members/{mid}][%d] deleteProjectsProjectIdMembersMidInternalServerError ", 500)
}

func (o *DeleteProjectsProjectIDMembersMidInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
