// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteProjectsProjectIDMembersMidParams creates a new DeleteProjectsProjectIDMembersMidParams object
// with the default values initialized.
func NewDeleteProjectsProjectIDMembersMidParams() *DeleteProjectsProjectIDMembersMidParams {
	var ()
	return &DeleteProjectsProjectIDMembersMidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProjectsProjectIDMembersMidParamsWithTimeout creates a new DeleteProjectsProjectIDMembersMidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteProjectsProjectIDMembersMidParamsWithTimeout(timeout time.Duration) *DeleteProjectsProjectIDMembersMidParams {
	var ()
	return &DeleteProjectsProjectIDMembersMidParams{

		timeout: timeout,
	}
}

// NewDeleteProjectsProjectIDMembersMidParamsWithContext creates a new DeleteProjectsProjectIDMembersMidParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteProjectsProjectIDMembersMidParamsWithContext(ctx context.Context) *DeleteProjectsProjectIDMembersMidParams {
	var ()
	return &DeleteProjectsProjectIDMembersMidParams{

		Context: ctx,
	}
}

// NewDeleteProjectsProjectIDMembersMidParamsWithHTTPClient creates a new DeleteProjectsProjectIDMembersMidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteProjectsProjectIDMembersMidParamsWithHTTPClient(client *http.Client) *DeleteProjectsProjectIDMembersMidParams {
	var ()
	return &DeleteProjectsProjectIDMembersMidParams{
		HTTPClient: client,
	}
}

/*DeleteProjectsProjectIDMembersMidParams contains all the parameters to send to the API endpoint
for the delete projects project ID members mid operation typically these are written to a http.Request
*/
type DeleteProjectsProjectIDMembersMidParams struct {

	/*Mid
	  Member ID.

	*/
	Mid int64
	/*ProjectID
	  Relevant project ID.

	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) WithTimeout(timeout time.Duration) *DeleteProjectsProjectIDMembersMidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) WithContext(ctx context.Context) *DeleteProjectsProjectIDMembersMidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) WithHTTPClient(client *http.Client) *DeleteProjectsProjectIDMembersMidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMid adds the mid to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) WithMid(mid int64) *DeleteProjectsProjectIDMembersMidParams {
	o.SetMid(mid)
	return o
}

// SetMid adds the mid to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) SetMid(mid int64) {
	o.Mid = mid
}

// WithProjectID adds the projectID to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) WithProjectID(projectID int64) *DeleteProjectsProjectIDMembersMidParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete projects project ID members mid params
func (o *DeleteProjectsProjectIDMembersMidParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProjectsProjectIDMembersMidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param mid
	if err := r.SetPathParam("mid", swag.FormatInt64(o.Mid)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
