// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteReplicationPoliciesIDParams creates a new DeleteReplicationPoliciesIDParams object
// with the default values initialized.
func NewDeleteReplicationPoliciesIDParams() *DeleteReplicationPoliciesIDParams {
	var ()
	return &DeleteReplicationPoliciesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteReplicationPoliciesIDParamsWithTimeout creates a new DeleteReplicationPoliciesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteReplicationPoliciesIDParamsWithTimeout(timeout time.Duration) *DeleteReplicationPoliciesIDParams {
	var ()
	return &DeleteReplicationPoliciesIDParams{

		timeout: timeout,
	}
}

// NewDeleteReplicationPoliciesIDParamsWithContext creates a new DeleteReplicationPoliciesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteReplicationPoliciesIDParamsWithContext(ctx context.Context) *DeleteReplicationPoliciesIDParams {
	var ()
	return &DeleteReplicationPoliciesIDParams{

		Context: ctx,
	}
}

// NewDeleteReplicationPoliciesIDParamsWithHTTPClient creates a new DeleteReplicationPoliciesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteReplicationPoliciesIDParamsWithHTTPClient(client *http.Client) *DeleteReplicationPoliciesIDParams {
	var ()
	return &DeleteReplicationPoliciesIDParams{
		HTTPClient: client,
	}
}

/*DeleteReplicationPoliciesIDParams contains all the parameters to send to the API endpoint
for the delete replication policies ID operation typically these are written to a http.Request
*/
type DeleteReplicationPoliciesIDParams struct {

	/*ID
	  Replication policy ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete replication policies ID params
func (o *DeleteReplicationPoliciesIDParams) WithTimeout(timeout time.Duration) *DeleteReplicationPoliciesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete replication policies ID params
func (o *DeleteReplicationPoliciesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete replication policies ID params
func (o *DeleteReplicationPoliciesIDParams) WithContext(ctx context.Context) *DeleteReplicationPoliciesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete replication policies ID params
func (o *DeleteReplicationPoliciesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete replication policies ID params
func (o *DeleteReplicationPoliciesIDParams) WithHTTPClient(client *http.Client) *DeleteReplicationPoliciesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete replication policies ID params
func (o *DeleteReplicationPoliciesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete replication policies ID params
func (o *DeleteReplicationPoliciesIDParams) WithID(id int64) *DeleteReplicationPoliciesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete replication policies ID params
func (o *DeleteReplicationPoliciesIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteReplicationPoliciesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
