// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectsProjectIDWebhookEventsParams creates a new GetProjectsProjectIDWebhookEventsParams object
// with the default values initialized.
func NewGetProjectsProjectIDWebhookEventsParams() *GetProjectsProjectIDWebhookEventsParams {
	var ()
	return &GetProjectsProjectIDWebhookEventsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectsProjectIDWebhookEventsParamsWithTimeout creates a new GetProjectsProjectIDWebhookEventsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProjectsProjectIDWebhookEventsParamsWithTimeout(timeout time.Duration) *GetProjectsProjectIDWebhookEventsParams {
	var ()
	return &GetProjectsProjectIDWebhookEventsParams{

		timeout: timeout,
	}
}

// NewGetProjectsProjectIDWebhookEventsParamsWithContext creates a new GetProjectsProjectIDWebhookEventsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProjectsProjectIDWebhookEventsParamsWithContext(ctx context.Context) *GetProjectsProjectIDWebhookEventsParams {
	var ()
	return &GetProjectsProjectIDWebhookEventsParams{

		Context: ctx,
	}
}

// NewGetProjectsProjectIDWebhookEventsParamsWithHTTPClient creates a new GetProjectsProjectIDWebhookEventsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProjectsProjectIDWebhookEventsParamsWithHTTPClient(client *http.Client) *GetProjectsProjectIDWebhookEventsParams {
	var ()
	return &GetProjectsProjectIDWebhookEventsParams{
		HTTPClient: client,
	}
}

/*GetProjectsProjectIDWebhookEventsParams contains all the parameters to send to the API endpoint
for the get projects project ID webhook events operation typically these are written to a http.Request
*/
type GetProjectsProjectIDWebhookEventsParams struct {

	/*ProjectID
	  Relevant project ID.

	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get projects project ID webhook events params
func (o *GetProjectsProjectIDWebhookEventsParams) WithTimeout(timeout time.Duration) *GetProjectsProjectIDWebhookEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get projects project ID webhook events params
func (o *GetProjectsProjectIDWebhookEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get projects project ID webhook events params
func (o *GetProjectsProjectIDWebhookEventsParams) WithContext(ctx context.Context) *GetProjectsProjectIDWebhookEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get projects project ID webhook events params
func (o *GetProjectsProjectIDWebhookEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get projects project ID webhook events params
func (o *GetProjectsProjectIDWebhookEventsParams) WithHTTPClient(client *http.Client) *GetProjectsProjectIDWebhookEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get projects project ID webhook events params
func (o *GetProjectsProjectIDWebhookEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get projects project ID webhook events params
func (o *GetProjectsProjectIDWebhookEventsParams) WithProjectID(projectID int64) *GetProjectsProjectIDWebhookEventsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get projects project ID webhook events params
func (o *GetProjectsProjectIDWebhookEventsParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectsProjectIDWebhookEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
