// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRetentionsMetadatasParams creates a new GetRetentionsMetadatasParams object
// with the default values initialized.
func NewGetRetentionsMetadatasParams() *GetRetentionsMetadatasParams {

	return &GetRetentionsMetadatasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRetentionsMetadatasParamsWithTimeout creates a new GetRetentionsMetadatasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRetentionsMetadatasParamsWithTimeout(timeout time.Duration) *GetRetentionsMetadatasParams {

	return &GetRetentionsMetadatasParams{

		timeout: timeout,
	}
}

// NewGetRetentionsMetadatasParamsWithContext creates a new GetRetentionsMetadatasParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRetentionsMetadatasParamsWithContext(ctx context.Context) *GetRetentionsMetadatasParams {

	return &GetRetentionsMetadatasParams{

		Context: ctx,
	}
}

// NewGetRetentionsMetadatasParamsWithHTTPClient creates a new GetRetentionsMetadatasParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRetentionsMetadatasParamsWithHTTPClient(client *http.Client) *GetRetentionsMetadatasParams {

	return &GetRetentionsMetadatasParams{
		HTTPClient: client,
	}
}

/*GetRetentionsMetadatasParams contains all the parameters to send to the API endpoint
for the get retentions metadatas operation typically these are written to a http.Request
*/
type GetRetentionsMetadatasParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get retentions metadatas params
func (o *GetRetentionsMetadatasParams) WithTimeout(timeout time.Duration) *GetRetentionsMetadatasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get retentions metadatas params
func (o *GetRetentionsMetadatasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get retentions metadatas params
func (o *GetRetentionsMetadatasParams) WithContext(ctx context.Context) *GetRetentionsMetadatasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get retentions metadatas params
func (o *GetRetentionsMetadatasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get retentions metadatas params
func (o *GetRetentionsMetadatasParams) WithHTTPClient(client *http.Client) *GetRetentionsMetadatasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get retentions metadatas params
func (o *GetRetentionsMetadatasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRetentionsMetadatasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
