// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectsProjectIDMembersMidParams creates a new GetProjectsProjectIDMembersMidParams object
// with the default values initialized.
func NewGetProjectsProjectIDMembersMidParams() *GetProjectsProjectIDMembersMidParams {
	var ()
	return &GetProjectsProjectIDMembersMidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectsProjectIDMembersMidParamsWithTimeout creates a new GetProjectsProjectIDMembersMidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProjectsProjectIDMembersMidParamsWithTimeout(timeout time.Duration) *GetProjectsProjectIDMembersMidParams {
	var ()
	return &GetProjectsProjectIDMembersMidParams{

		timeout: timeout,
	}
}

// NewGetProjectsProjectIDMembersMidParamsWithContext creates a new GetProjectsProjectIDMembersMidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProjectsProjectIDMembersMidParamsWithContext(ctx context.Context) *GetProjectsProjectIDMembersMidParams {
	var ()
	return &GetProjectsProjectIDMembersMidParams{

		Context: ctx,
	}
}

// NewGetProjectsProjectIDMembersMidParamsWithHTTPClient creates a new GetProjectsProjectIDMembersMidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProjectsProjectIDMembersMidParamsWithHTTPClient(client *http.Client) *GetProjectsProjectIDMembersMidParams {
	var ()
	return &GetProjectsProjectIDMembersMidParams{
		HTTPClient: client,
	}
}

/*GetProjectsProjectIDMembersMidParams contains all the parameters to send to the API endpoint
for the get projects project ID members mid operation typically these are written to a http.Request
*/
type GetProjectsProjectIDMembersMidParams struct {

	/*Mid
	  The member ID

	*/
	Mid int64
	/*ProjectID
	  Relevant project ID.

	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) WithTimeout(timeout time.Duration) *GetProjectsProjectIDMembersMidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) WithContext(ctx context.Context) *GetProjectsProjectIDMembersMidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) WithHTTPClient(client *http.Client) *GetProjectsProjectIDMembersMidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMid adds the mid to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) WithMid(mid int64) *GetProjectsProjectIDMembersMidParams {
	o.SetMid(mid)
	return o
}

// SetMid adds the mid to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) SetMid(mid int64) {
	o.Mid = mid
}

// WithProjectID adds the projectID to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) WithProjectID(projectID int64) *GetProjectsProjectIDMembersMidParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get projects project ID members mid params
func (o *GetProjectsProjectIDMembersMidParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectsProjectIDMembersMidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param mid
	if err := r.SetPathParam("mid", swag.FormatInt64(o.Mid)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
