// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReplicationAdaptersParams creates a new GetReplicationAdaptersParams object
// with the default values initialized.
func NewGetReplicationAdaptersParams() *GetReplicationAdaptersParams {

	return &GetReplicationAdaptersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReplicationAdaptersParamsWithTimeout creates a new GetReplicationAdaptersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReplicationAdaptersParamsWithTimeout(timeout time.Duration) *GetReplicationAdaptersParams {

	return &GetReplicationAdaptersParams{

		timeout: timeout,
	}
}

// NewGetReplicationAdaptersParamsWithContext creates a new GetReplicationAdaptersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReplicationAdaptersParamsWithContext(ctx context.Context) *GetReplicationAdaptersParams {

	return &GetReplicationAdaptersParams{

		Context: ctx,
	}
}

// NewGetReplicationAdaptersParamsWithHTTPClient creates a new GetReplicationAdaptersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReplicationAdaptersParamsWithHTTPClient(client *http.Client) *GetReplicationAdaptersParams {

	return &GetReplicationAdaptersParams{
		HTTPClient: client,
	}
}

/*GetReplicationAdaptersParams contains all the parameters to send to the API endpoint
for the get replication adapters operation typically these are written to a http.Request
*/
type GetReplicationAdaptersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get replication adapters params
func (o *GetReplicationAdaptersParams) WithTimeout(timeout time.Duration) *GetReplicationAdaptersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get replication adapters params
func (o *GetReplicationAdaptersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get replication adapters params
func (o *GetReplicationAdaptersParams) WithContext(ctx context.Context) *GetReplicationAdaptersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get replication adapters params
func (o *GetReplicationAdaptersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get replication adapters params
func (o *GetReplicationAdaptersParams) WithHTTPClient(client *http.Client) *GetReplicationAdaptersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get replication adapters params
func (o *GetReplicationAdaptersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetReplicationAdaptersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
