// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScansAllMetricsParams creates a new GetScansAllMetricsParams object
// with the default values initialized.
func NewGetScansAllMetricsParams() *GetScansAllMetricsParams {

	return &GetScansAllMetricsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScansAllMetricsParamsWithTimeout creates a new GetScansAllMetricsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScansAllMetricsParamsWithTimeout(timeout time.Duration) *GetScansAllMetricsParams {

	return &GetScansAllMetricsParams{

		timeout: timeout,
	}
}

// NewGetScansAllMetricsParamsWithContext creates a new GetScansAllMetricsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScansAllMetricsParamsWithContext(ctx context.Context) *GetScansAllMetricsParams {

	return &GetScansAllMetricsParams{

		Context: ctx,
	}
}

// NewGetScansAllMetricsParamsWithHTTPClient creates a new GetScansAllMetricsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScansAllMetricsParamsWithHTTPClient(client *http.Client) *GetScansAllMetricsParams {

	return &GetScansAllMetricsParams{
		HTTPClient: client,
	}
}

/*GetScansAllMetricsParams contains all the parameters to send to the API endpoint
for the get scans all metrics operation typically these are written to a http.Request
*/
type GetScansAllMetricsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scans all metrics params
func (o *GetScansAllMetricsParams) WithTimeout(timeout time.Duration) *GetScansAllMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scans all metrics params
func (o *GetScansAllMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scans all metrics params
func (o *GetScansAllMetricsParams) WithContext(ctx context.Context) *GetScansAllMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scans all metrics params
func (o *GetScansAllMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scans all metrics params
func (o *GetScansAllMetricsParams) WithHTTPClient(client *http.Client) *GetScansAllMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scans all metrics params
func (o *GetScansAllMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetScansAllMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
