// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScannersRegistrationIDMetadataParams creates a new GetScannersRegistrationIDMetadataParams object
// with the default values initialized.
func NewGetScannersRegistrationIDMetadataParams() *GetScannersRegistrationIDMetadataParams {
	var ()
	return &GetScannersRegistrationIDMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScannersRegistrationIDMetadataParamsWithTimeout creates a new GetScannersRegistrationIDMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScannersRegistrationIDMetadataParamsWithTimeout(timeout time.Duration) *GetScannersRegistrationIDMetadataParams {
	var ()
	return &GetScannersRegistrationIDMetadataParams{

		timeout: timeout,
	}
}

// NewGetScannersRegistrationIDMetadataParamsWithContext creates a new GetScannersRegistrationIDMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScannersRegistrationIDMetadataParamsWithContext(ctx context.Context) *GetScannersRegistrationIDMetadataParams {
	var ()
	return &GetScannersRegistrationIDMetadataParams{

		Context: ctx,
	}
}

// NewGetScannersRegistrationIDMetadataParamsWithHTTPClient creates a new GetScannersRegistrationIDMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScannersRegistrationIDMetadataParamsWithHTTPClient(client *http.Client) *GetScannersRegistrationIDMetadataParams {
	var ()
	return &GetScannersRegistrationIDMetadataParams{
		HTTPClient: client,
	}
}

/*GetScannersRegistrationIDMetadataParams contains all the parameters to send to the API endpoint
for the get scanners registration ID metadata operation typically these are written to a http.Request
*/
type GetScannersRegistrationIDMetadataParams struct {

	/*RegistrationID
	  The scanner registration identifier.

	*/
	RegistrationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scanners registration ID metadata params
func (o *GetScannersRegistrationIDMetadataParams) WithTimeout(timeout time.Duration) *GetScannersRegistrationIDMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scanners registration ID metadata params
func (o *GetScannersRegistrationIDMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scanners registration ID metadata params
func (o *GetScannersRegistrationIDMetadataParams) WithContext(ctx context.Context) *GetScannersRegistrationIDMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scanners registration ID metadata params
func (o *GetScannersRegistrationIDMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scanners registration ID metadata params
func (o *GetScannersRegistrationIDMetadataParams) WithHTTPClient(client *http.Client) *GetScannersRegistrationIDMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scanners registration ID metadata params
func (o *GetScannersRegistrationIDMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegistrationID adds the registrationID to the get scanners registration ID metadata params
func (o *GetScannersRegistrationIDMetadataParams) WithRegistrationID(registrationID string) *GetScannersRegistrationIDMetadataParams {
	o.SetRegistrationID(registrationID)
	return o
}

// SetRegistrationID adds the registrationId to the get scanners registration ID metadata params
func (o *GetScannersRegistrationIDMetadataParams) SetRegistrationID(registrationID string) {
	o.RegistrationID = registrationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetScannersRegistrationIDMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param registration_id
	if err := r.SetPathParam("registration_id", o.RegistrationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
