// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutSystemGcScheduleReader is a Reader for the PutSystemGcSchedule structure.
type PutSystemGcScheduleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutSystemGcScheduleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutSystemGcScheduleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutSystemGcScheduleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutSystemGcScheduleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutSystemGcScheduleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutSystemGcScheduleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutSystemGcScheduleOK creates a PutSystemGcScheduleOK with default headers values
func NewPutSystemGcScheduleOK() *PutSystemGcScheduleOK {
	return &PutSystemGcScheduleOK{}
}

/*PutSystemGcScheduleOK handles this case with default header values.

Updated gc's schedule successfully.
*/
type PutSystemGcScheduleOK struct {
}

func (o *PutSystemGcScheduleOK) Error() string {
	return fmt.Sprintf("[PUT /system/gc/schedule][%d] putSystemGcScheduleOK ", 200)
}

func (o *PutSystemGcScheduleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutSystemGcScheduleBadRequest creates a PutSystemGcScheduleBadRequest with default headers values
func NewPutSystemGcScheduleBadRequest() *PutSystemGcScheduleBadRequest {
	return &PutSystemGcScheduleBadRequest{}
}

/*PutSystemGcScheduleBadRequest handles this case with default header values.

Invalid schedule type.
*/
type PutSystemGcScheduleBadRequest struct {
}

func (o *PutSystemGcScheduleBadRequest) Error() string {
	return fmt.Sprintf("[PUT /system/gc/schedule][%d] putSystemGcScheduleBadRequest ", 400)
}

func (o *PutSystemGcScheduleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutSystemGcScheduleUnauthorized creates a PutSystemGcScheduleUnauthorized with default headers values
func NewPutSystemGcScheduleUnauthorized() *PutSystemGcScheduleUnauthorized {
	return &PutSystemGcScheduleUnauthorized{}
}

/*PutSystemGcScheduleUnauthorized handles this case with default header values.

User need to log in first.
*/
type PutSystemGcScheduleUnauthorized struct {
}

func (o *PutSystemGcScheduleUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /system/gc/schedule][%d] putSystemGcScheduleUnauthorized ", 401)
}

func (o *PutSystemGcScheduleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutSystemGcScheduleForbidden creates a PutSystemGcScheduleForbidden with default headers values
func NewPutSystemGcScheduleForbidden() *PutSystemGcScheduleForbidden {
	return &PutSystemGcScheduleForbidden{}
}

/*PutSystemGcScheduleForbidden handles this case with default header values.

User does not have permission of admin role.
*/
type PutSystemGcScheduleForbidden struct {
}

func (o *PutSystemGcScheduleForbidden) Error() string {
	return fmt.Sprintf("[PUT /system/gc/schedule][%d] putSystemGcScheduleForbidden ", 403)
}

func (o *PutSystemGcScheduleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutSystemGcScheduleInternalServerError creates a PutSystemGcScheduleInternalServerError with default headers values
func NewPutSystemGcScheduleInternalServerError() *PutSystemGcScheduleInternalServerError {
	return &PutSystemGcScheduleInternalServerError{}
}

/*PutSystemGcScheduleInternalServerError handles this case with default header values.

Unexpected internal errors.
*/
type PutSystemGcScheduleInternalServerError struct {
}

func (o *PutSystemGcScheduleInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /system/gc/schedule][%d] putSystemGcScheduleInternalServerError ", 500)
}

func (o *PutSystemGcScheduleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
