// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPutUsersUserIDCliSecretParams creates a new PutUsersUserIDCliSecretParams object
// with the default values initialized.
func NewPutUsersUserIDCliSecretParams() *PutUsersUserIDCliSecretParams {
	var ()
	return &PutUsersUserIDCliSecretParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutUsersUserIDCliSecretParamsWithTimeout creates a new PutUsersUserIDCliSecretParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutUsersUserIDCliSecretParamsWithTimeout(timeout time.Duration) *PutUsersUserIDCliSecretParams {
	var ()
	return &PutUsersUserIDCliSecretParams{

		timeout: timeout,
	}
}

// NewPutUsersUserIDCliSecretParamsWithContext creates a new PutUsersUserIDCliSecretParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutUsersUserIDCliSecretParamsWithContext(ctx context.Context) *PutUsersUserIDCliSecretParams {
	var ()
	return &PutUsersUserIDCliSecretParams{

		Context: ctx,
	}
}

// NewPutUsersUserIDCliSecretParamsWithHTTPClient creates a new PutUsersUserIDCliSecretParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutUsersUserIDCliSecretParamsWithHTTPClient(client *http.Client) *PutUsersUserIDCliSecretParams {
	var ()
	return &PutUsersUserIDCliSecretParams{
		HTTPClient: client,
	}
}

/*PutUsersUserIDCliSecretParams contains all the parameters to send to the API endpoint
for the put users user ID cli secret operation typically these are written to a http.Request
*/
type PutUsersUserIDCliSecretParams struct {

	/*InputSecret
	  JSON object that includes the new secret

	*/
	InputSecret PutUsersUserIDCliSecretBody
	/*UserID
	  User ID

	*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) WithTimeout(timeout time.Duration) *PutUsersUserIDCliSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) WithContext(ctx context.Context) *PutUsersUserIDCliSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) WithHTTPClient(client *http.Client) *PutUsersUserIDCliSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInputSecret adds the inputSecret to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) WithInputSecret(inputSecret PutUsersUserIDCliSecretBody) *PutUsersUserIDCliSecretParams {
	o.SetInputSecret(inputSecret)
	return o
}

// SetInputSecret adds the inputSecret to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) SetInputSecret(inputSecret PutUsersUserIDCliSecretBody) {
	o.InputSecret = inputSecret
}

// WithUserID adds the userID to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) WithUserID(userID int64) *PutUsersUserIDCliSecretParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the put users user ID cli secret params
func (o *PutUsersUserIDCliSecretParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *PutUsersUserIDCliSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.InputSecret); err != nil {
		return err
	}

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
