// Code generated by "stringer -type=ControllerUID -linecomment"; DO NOT EDIT.

package setup

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Harbor-0]
	_ = x[Core-1]
	_ = x[JobService-2]
	_ = x[Registry-3]
	_ = x[NotaryServer-4]
	_ = x[NotarySigner-5]
	_ = x[RegistryCtl-6]
	_ = x[Portal-7]
	_ = x[ChartMuseum-8]
}

const _ControllerUID_name = "harborcorejobserviceregistrynotary-servernotary-signerregistryctlportalchartmuseum"

var _ControllerUID_index = [...]uint8{0, 6, 10, 20, 28, 41, 54, 65, 71, 82}

func (i ControllerUID) String() string {
	if i < 0 || i >= ControllerUID(len(_ControllerUID_index)-1) {
		return "ControllerUID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ControllerUID_name[_ControllerUID_index[i]:_ControllerUID_index[i+1]]
}
