// Code generated by go-swagger; DO NOT EDIT.

package auditlog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new auditlog API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for auditlog API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ListAuditLogs(params *ListAuditLogsParams, authInfo runtime.ClientAuthInfoWriter) (*ListAuditLogsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ListAuditLogs gets recent logs of the projects which the user is a member of

  This endpoint let user see the recent operation logs of the projects which he is member of

*/
func (a *Client) ListAuditLogs(params *ListAuditLogsParams, authInfo runtime.ClientAuthInfoWriter) (*ListAuditLogsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListAuditLogsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listAuditLogs",
		Method:             "GET",
		PathPattern:        "/audit-logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListAuditLogsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListAuditLogsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listAuditLogs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
