apiVersion: goharbor.io/v1alpha2
kind: Registry
metadata:
  name: harbor
spec:
  version: "1.10.0"
  replicas: 1
  certificateIssuerRef:
    name: harbor-sample
    kind: Issuer
    group: cert-manager.io
  publicURL: https://registry.com
  configName: sample-registry-configuration
  cacheSecret: sample-registry-cache
  storageSecret: sample-registry-storage
