apiVersion: goharbor.io/v1alpha2
kind: Registry
metadata:
  name: harbor
spec:
  storage:
    driverName: inmemory
    cache:
      blobdescriptor: redis
  authentication:
    htPasswd: 
      realm: "harbor-registry"
      secretRef: registry-htpasswd
  redis:
    dsn: redis://admin@harbor-redis-master:6379/2
    passwordRef: harbor-redis
  http:
    secretRef: registry-secret
