storage:
  delete:
    enabled: true
  redirect:
    disable: false
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: false
    readonly:
      enabled: false
  inmemory: {}
