apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  sample: "true"

resources:
- https.yaml
- service_token_issuer.yaml
- storage.yaml
- goharbor_v1alpha3_harbor.yaml

secretGenerator:
- name: admin-core-secret
  literals:
  - secret=Harbor12345
  type: "goharbor.io/single-secret"

bases:
- ../../kustomizeconfig

patchesStrategicMerge:
  - images_patch.yaml
