apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-harbor-registry
  labels:
    goharbor.io/component: registry
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
