generatorOptions:
  disableNameSuffixHash: true

namePrefix: '{{ include "chart.fullname" . }}-'

namespace: '{{ .Release.Namespace }}'

patchesStrategicMerge:
- certificate_secret_patch.yaml

bases:
- ../../certmanager
