namePrefix: '{{ include "chart.fullname" . }}-'

namespace: '{{ .Release.Namespace | quote }}'

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- patch_certificate_dns.yaml
- patch_certificate_secret.yaml

bases:
- ../../certmanager
