name: Generate

on:
  push:
    branches:
    - master

jobs:
  plantuml:
    name: Generate PlantUML diagrams
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate images
      uses: grassedge/generate-plantuml-action@v1.1
      with:
        path: docs/images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
